/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // SwasthyaLink / JeevanDoot palette backed by RGB-triplet CSS custom
        // properties (src/styles/variables.css). The <alpha-value> placeholder
        // keeps opacity modifiers (e.g. bg-primary/40) working; light/dark
        // themes swap automatically via the `.dark` class.
        primary: 'rgb(var(--jd-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--jd-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--jd-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--jd-on-primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--jd-primary-fixed) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--jd-on-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--jd-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--jd-on-primary-fixed-variant) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--jd-inverse-primary) / <alpha-value>)',
        secondary: 'rgb(var(--jd-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--jd-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--jd-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--jd-on-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--jd-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--jd-on-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--jd-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--jd-on-secondary-fixed-variant) / <alpha-value>)',
        tertiary: 'rgb(var(--jd-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--jd-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--jd-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--jd-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--jd-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--jd-on-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--jd-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--jd-on-tertiary-fixed-variant) / <alpha-value>)',
        error: 'rgb(var(--jd-error) / <alpha-value>)',
        'on-error': 'rgb(var(--jd-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--jd-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--jd-on-error-container) / <alpha-value>)',
        background: 'rgb(var(--jd-background) / <alpha-value>)',
        'on-background': 'rgb(var(--jd-on-background) / <alpha-value>)',
        surface: 'rgb(var(--jd-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--jd-on-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--jd-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--jd-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--jd-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--jd-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--jd-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--jd-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--jd-surface-container-highest) / <alpha-value>)',
        'surface-variant': 'rgb(var(--jd-surface-variant) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--jd-on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--jd-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--jd-outline-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--jd-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--jd-inverse-on-surface) / <alpha-value>)',
        'surface-tint': 'rgb(var(--jd-surface-tint) / <alpha-value>)',
        coral: 'rgb(var(--jd-coral) / <alpha-value>)',
        success: 'rgb(var(--jd-success) / <alpha-value>)',
        'on-success': 'rgb(var(--jd-on-success) / <alpha-value>)',
        'success-container': 'rgb(var(--jd-success-container) / <alpha-value>)',
        'on-success-container': 'rgb(var(--jd-on-success-container) / <alpha-value>)',
        warning: 'rgb(var(--jd-warning) / <alpha-value>)',
        'on-warning': 'rgb(var(--jd-on-warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--jd-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--jd-on-warning-container) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Literata', 'serif'],
        display: ['Literata', 'serif'],
        body: ['Atkinson Hyperlegible Next', 'sans-serif'],
        label: ['Atkinson Hyperlegible Next', 'sans-serif'],
      },
      fontSize: {
        'headline-2xl': ['3rem', '3.5rem'],
        'headline-xl': ['2.25rem', '2.75rem'],
        'headline-lg': ['2rem', '2.5rem'],
        'headline-md': ['1.5rem', '2rem'],
        'headline-sm': ['1.25rem', '1.75rem'],
        'title-lg': ['1.375rem', '1.75rem'],
        'title-md': ['1.125rem', '1.5rem'],
        'title-sm': ['1rem', '1.375rem'],
        'body-lg': ['1.125rem', '1.75rem'],
        'body-md': ['1rem', '1.5rem'],
        'body-sm': ['0.875rem', '1.25rem'],
        'label-lg': ['0.875rem', '1.25rem'],
        'label-md': ['0.75rem', '1rem'],
        'label-sm': ['0.6875rem', '1rem'],
      },
      boxShadow: {
        elevation1: '0px 4px 12px rgba(27, 94, 79, 0.08)',
        elevation2: '0px 8px 24px rgba(27, 94, 79, 0.12)',
        elevation3: '0px 12px 32px rgba(27, 94, 79, 0.16)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
