/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Material 3 "SwasthyaLink / JeevanDoot" palette (extracted from HTML prototypes)
        primary: '#004639',
        'on-primary': '#ffffff',
        'primary-container': '#1b5e4f',
        'on-primary-container': '#95d5c2',
        'primary-fixed': '#aff0dc',
        'on-primary-fixed': '#002019',
        'primary-fixed-dim': '#93d3c0',
        'on-primary-fixed-variant': '#055142',
        'inverse-primary': '#93d3c0',
        secondary: '#7c5800',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdbf40',
        'on-secondary-container': '#6f4e00',
        'secondary-fixed': '#ffdea8',
        'on-secondary-fixed': '#271900',
        'secondary-fixed-dim': '#fabc3e',
        'on-secondary-fixed-variant': '#5e4200',
        tertiary: '#722000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#933510',
        'on-tertiary-container': '#ffb7a0',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary-fixed': '#390c00',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-fixed-variant': '#822803',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fff9eb',
        'on-background': '#1e1c10',
        surface: '#fff9eb',
        'on-surface': '#1e1c10',
        'surface-dim': '#e0dac7',
        'surface-bright': '#fff9eb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf3e0',
        'surface-container': '#f4eedb',
        'surface-container-high': '#efe8d5',
        'surface-container-highest': '#e9e2d0',
        'surface-variant': '#e9e2d0',
        'on-surface-variant': '#3f4945',
        outline: '#707975',
        'outline-variant': '#bfc9c4',
        'inverse-surface': '#333024',
        'inverse-on-surface': '#f7f0de',
        'surface-tint': '#286959',
        coral: '#E8734A',
        success: '#1e6b3c',
        'on-success': '#ffffff',
        'success-container': '#d9f0e0',
        'on-success-container': '#0a3d1f',
        warning: '#b26a00',
        'on-warning': '#ffffff',
        'warning-container': '#ffdec7',
        'on-warning-container': '#3d1a00',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Literata', 'serif'],
        display: ['Literata', 'serif'],
        body: ['Atkinson Hyperlegible Next', 'sans-serif'],
        label: ['Atkinson Hyperlegible Next', 'sans-serif'],
      },
      fontSize: {
        'headline-2xl': ['3rem', '3.5rem'],
        'headline-xl': ['2.25rem', '2.75rem'],
        'headline-lg': ['2rem', '2.5rem'],
        'headline-md': ['1.5rem', '2rem'],
        'headline-sm': ['1.25rem', '1.75rem'],
        'title-lg': ['1.375rem', '1.75rem'],
        'title-md': ['1.125rem', '1.5rem'],
        'title-sm': ['1rem', '1.375rem'],
        'body-lg': ['1.125rem', '1.75rem'],
        'body-md': ['1rem', '1.5rem'],
        'body-sm': ['0.875rem', '1.25rem'],
        'label-lg': ['0.875rem', '1.25rem'],
        'label-md': ['0.75rem', '1rem'],
        'label-sm': ['0.6875rem', '1rem'],
      },
      boxShadow: {
        elevation1: '0px 4px 12px rgba(27, 94, 79, 0.08)',
        elevation2: '0px 8px 24px rgba(27, 94, 79, 0.12)',
        elevation3: '0px 12px 32px rgba(27, 94, 79, 0.16)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
